spring:
    application:
        name: teams-api
    web:
        locale: pt-br
        locale-resolver: fixed
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
    datasource:
        url: ${URL_DB_TEAMS}
        username: ${USER_DB_TEAMS}
        password: ${PASSWORD_DB_TEAMS}

server:
    error:
        include-stacktrace: never